#1 Sprint 1
OlegSharomov/java-filmorate pull request #1
Opened 2022-05-15 20:31 UTC by OlegSharomov

2022-05-16 23:05 UTC, ablohin requested changes
Молодец, всё сделано отлично. Исправляем мелкие замечания и сдаем работу на следующей итерации.

2022-05-16 23:05 UTC, ablohin commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +// Пока оставил комментарии, если что то не правильно понял - поправьте пожалуйста!
Да, всё верно описано.

2022-05-16 23:05 UTC, ablohin commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
Лучше использовать `import` для каждого класса отдельно, без использования символа астериска. Тем самым ты не столкнешься с проблемами конфликтов слияния при слияние веток при выставлении пул реквеста.

2022-05-17 20:15 UTC, ablohin approved these changes
Привет! Всё хорошо, задача принята, дорабатывать не нужно.

2022-05-19 08:01 UTC, OlegSharomov commented
> Привет! Всё хорошо, одобрена, дорабатывать не нужно.
Ветку сейчас нужно смержить? Через кнопку merge pull requesr или лучше через git?

2022-05-20 13:26 UTC, merged