Add friends likes
OlegSharomov/java-filmorate pull request #3
Opened 2022-06-13 16:37 UTC by OlegSharomov

2022-06-14 04:33 UTC, sergey-oreshkin requested changes
**таблица films**
- поле _rating_id_ лишнее. как и отдельная таблица под него. это вычисляемый параметр и может принимать значения на всем диапазоне своего типа, а значить таблица _film_rating_ будет просто заполнена всеми возможными числами. можно иметь просто поле rating и сохранять число прямо туда

**таблицы film_genre, friendship_list, friendship_request**
- не имеют первичного ключа(_film_genre_) или он не уникален. то есть в _friendship_list_, например, может быть несколько записей с одним и тем же _user_id_.  для уникальности в сводных таблицах нужно делать первичный ключ состоящий сразу из двух полей.

2022-06-14 16:09 UTC, sergey-oreshkin approved these changes
нормально.
только у нас по условию еще из 8 спринта у описания фильма длина 200. можно так и в БД установить

2022-06-15 04:38 UTC, sergey-oreshkin approved these changes
все ок

2022-06-15 15:28 UTC, lilyerma commented
Отличная работа! У тебя есть поле rating_id. Мне не совсем понятно, что это. Возможно, заготовка на будущее. В задании еще было "Там же напишите небольшое пояснение к схеме: приложите примеры запросов для основных операций вашего приложения." Я сделала, показалось очень полезно:)

2022-06-17 06:40 UTC, merged